services:
  basic-node-image:
    image: node:18.16.0
    working_dir: /vue-test
    ports: 
     - 4000:4000
  server:
    build:
      context: ./server
    ports: 
     - 3000:3000
    volumes:
     - ./server:/server:cached
