services:
  basic-node-image:
    image: node:18.16.0
    working_dir: /vue-test
    ports: 
     - 4000:4000

  server:
    build:
      context: ./server
    ports: 
     - 8545:8545
    volumes:
     - ./server:/app:cached

  metacoin:
    build:
      context: ./metacoin
    ports:
     - 8545:8545
    volumes:
     - ./metacoin:/app:cached
