services:
  basic-node-image:
    image: node:18.16.0
    working_dir: /vue-test
    ports: 
     - 4000:4000

  server:
    build:
      context: ./server
    ports: 
     - 8545:8545
    volumes:
     - ./server:/app:cached

  front-end:
    build:
      context: ./frontend
    ports:
     - 3000:3000
     - 8080:8080
     - 24678:24678
    volumes:
     - ./frontend:/frontend:cached
